#ifndef _STM32_IOCTL_H
#define _STM32_IOCTL_H
#include <linux/ioctl.h>

#define STM32_MAGIC_NUMBER 'k'
#define STM32_IOSETRDTOUT   _IO(STM32_MAGIC_NUMBER, 0)
#define STM32_IOSETWRTOUT   _IO(STM32_MAGIC_NUMBER, 1)
#define STM32_IOGETRDTOUT   _IO(STM32_MAGIC_NUMBER, 2)
#define STM32_IOGETWRTOUT   _IO(STM32_MAGIC_NUMBER, 3)
#define STM32_IORESETRDTOUT _IO(STM32_MAGIC_NUMBER, 4)
#define STM32_IORESETWRTOUT _IO(STM32_MAGIC_NUMBER, 5)
#define STM32_IOGETARMMODE  _IO(STM32_MAGIC_NUMBER, 6)

#define STM32_IOC_MAXNR 14


enum
{
	USB_ARM_MODE_INVALID= 0,
	USB_ARM_MODE_MAINAPP ,
	USB_ARM_MODE_BTL,
};

#endif//_STM32_IOCTL_H
